language: node_js
node_js:
- '6.1'
sudo: false
install:
- npm install
script:
- npm test
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: vc05C0msYOb1+JF4FixqslgJuBgWoex9y7/tlW4ZQJYlgV9fqFwbagzq4SOIXA/z1Q3D/V5SFpeValujG6yc8e7DZsYicKnN7DuAIPxE1eemOQiUttSwOnqSenCDwgzGQdoJ5MTyU20IeXauTyU5WZgPp5oWfZTVkv79yprdzUqCrYnkvvJpDK7AxKamGxkcpNYs4NUHVxR9u73ugtGLeb7r93jvYJ0uyDxU4IF9RRmYY7Hbcx1Fa59JcyGunlicFtauVbbyS5GiikADdaxsmSe65ZMjnYGgrhMdBm8zTOblg+ALT3KtW+V0S4TiuEH9e2F2iKBDSw+gXAUrllMj3/5RsVtgAwnkq3PYJpO3RC5k23dhnSqjMMQbtqXCS5xiOXUoUwMRF98SP9dr4iN1FJVAz8D8Cj37CUVeadgNw2XfHXx00I8bvpnETXsmYTBGrY89iB+lzeQe1Y6KwShXWALm/sUjv7izutdGO8sAVoTEMfkYwDQiEySnh7HPmWeJ1TqOO9db5cx+AtGu1y2tB5KoiKb1CgkXglbEIT3tRMxf+M++DKhZixXAaNhxbcUAFEjTPYmwDMaCLTrhrtFucE1Sm4qaqlp4Evfdr89BXnCxq2vwPyiCHrlBzeOZPBYbntH9IkVJA+SBMnJcnnVbCoC8bSfGh1vM1GwC10gP22A=
